image: $DOCKER_REGISTRY/maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "-B -Dbuild.number=${CI_PIPELINE_ID} -Dbuild.id=${CI_JOB_ID} -Dgit.branch=${CI_COMMIT_REF_NAME}"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dhttps.protocols=TLSv1.2"
  DOCKER_REGISTRY: "nexusrepo.smart-consulting.ru"

cache:
  paths:
    - .m2/repository/
    - $JAR

stages:
  - test
  - build


test:
  stage: test
  script:
    - echo "Start running tests"
    - mvn $MAVEN_CLI_OPTS clean test
    - echo "Test successfully complete"
  only:
    - merge_requests


build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - $JAR
  only:
    - merge_requests
    - master
